data_cfg:
  dataset_name: CASIA-B
  dataset_root: /root/data5/hxi/GaitRecognition/GaitDB/CASIA-B/CASIA-B-pkl
  dataset_partition: ./datasets/CASIA-B/CASIA-B.json
  num_workers: 0
  # remove_no_gallery: false
  test_dataset_name: CASIA-B
  cache: true


trainer_cfg:
  find_unused_parameters: false
  enable_float16: true
  with_test: true
  log_iter: 100
  restore_ckpt_strict: true # If True, check whether the checkpoint is the same as the defined model.
  restore_hint: 0
  optimizer_reset: false
  scheduler_reset: false
  save_iter: 10000
  save_name: GaitGL
  sync_BN: true
  fix_BN: false
  total_iter: 80000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8
      - 8
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
  - type: BaseSilCuttingTransform


evaluator_cfg:
  enable_float16: false
  restore_ckpt_strict: true
  restore_hint: 80000
  save_name: GaitGL
  eval_func: evaluate_indoor_dataset
  sampler:
    batch_size: 8 # the batch_size should be equal to the gpus number at the test phase!!!
    sample_type: all_ordered
    type: InferenceSampler
  transform:
    - type: BaseSilCuttingTransform
  metric: euc # cos
  cross_view_gallery: false



loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: false
    log_prefix: softmax


loss_map:
  loss: CE
  gamma:
    - 1
    - 1
    - 1
    - 1 
    - 1
  eta:
    - 1
    - 1
    - 1
    - 1 
    - 1 


optimizer_cfg:
  # lr: 1.0e-4
  # solver: Adam
  # weight_decay: 5.0e-4 
  lr: 0.1
  momentum: 0.9
  weight_decay: 5.0e-4
  nesterov: true
  solver: SGD


scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 20000
    - 40000
    - 50000
  scheduler: MultiStepLR


model_cfg:
  student: GaitGL
  teachers:
    - name: GaitSet
      restore_hint: 40000
      load_ckpt_strict: false # If True, check whether the checkpoint is the same as the defined model.
    - name: GaitPart
      restore_hint: 120000
      load_ckpt_strict: false
    - name: GaitGL
      restore_hint: 80000
      load_ckpt_strict: false
    - name: Baseline_ResNet9
      restore_hint: 60000
      load_ckpt_strict: true
  teacher_eval: false  # use teacher.eval() or not
  discriminator:  
    adv: true  # add discriminator or not
    grl: false  # 反向传播时，梯度取反
    d_lr: 0.1 # discriminator learning rate
  fc_out: true # if immediate output from fc-layer
  pool_out: max  # the type of pooling layer of output, max or avg
  out_layer:
    # - -1
    - 0
    - 1
    - 2
    - 3
    - 4
  out_dims: # the dims of output pooling layers
    - 5000
    - 1000
    - 500
    - 200 
    - 10