data_cfg:
  dataset_name: CASIA-B
  dataset_root: /root/data5/hxi/GaitRecognition/GaitDB/CASIA-B/CASIA-B-pkl
  dataset_partition: ./datasets/CASIA-B/CASIA-B.json
  num_workers: 0
  # remove_no_gallery: false
  # test_dataset_name: CASIA-B
  cache: true


trainer_cfg:
  find_unused_parameters: false
  enable_float16: true
  with_test: false
  log_iter: 100
  optimizer_reset: true
  scheduler_reset: true
  save_name: save_name
  sync_BN: true
  fix_BN: false
  restore_hint: 0
  sampler:
    batch_shuffle: true
    batch_size:
      - 8
      - 8
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
  - type: Compose
    trf_cfg:
      - type: BaseSilCuttingTransform
      - type: RandomRotate
        prob: 0.3
      - type: RandomErasing
        prob: 0.3


evaluator_cfg:
  enable_float16: false 
  sampler:
    batch_size: 8 
    sample_type: all_ordered
    type: InferenceSampler
  save_name: save_name
  restore_hint: 0
  transform:
  - type: BaseSilCuttingTransform


loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: false
    log_prefix: softmax

loss_map:
  loss: CE
  gamma:
    - 1
    - 1
    - 1
    - 1 
    - 1
  eta:
    - 1
    - 1
    - 1
    - 1 
    - 1 



optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  nesterov: true
  solver: SGD

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 20000
    - 40000
    - 50000
  scheduler: MultiStepLR



model_cfg:
  student: GaitGL
  teachers:
    - name: GaitSet
      restore_hint: 40000
      load_ckpt_strict: true # If True, check whether the checkpoint is the same as the defined model.
    - name: GaitPart
      restore_hint: 120000
      load_ckpt_strict: true
    - name: GaitGL
      restore_hint: 80000
      load_ckpt_strict: true
    - name: Baseline_ResNet9
      restore_hint: 60000
      load_ckpt_strict: true
  teacher_eval: false  # use teacher.eval() or not
  discriminator:  
    adv: true  # add discriminator or not
    grl: false  # 反向传播时，梯度取反
    d_lr: 0.1 # discriminator learning rate
