data_cfg:
  dataset_name: CASIA-B
  dataset_root: /root/data5/hxi/GaitRecognition/GaitDB/CASIA-B/CASIA-B-pkl
  dataset_partition: ./datasets/CASIA-B/CASIA-B.json
  num_workers: 0
  # remove_no_gallery: false
  # test_dataset_name: CASIA-B
  cache: true
  steps_per_epoch: 0


trainer_cfg:
  transform:
  - type: Compose
    trf_cfg:
      - type: BaseSilCuttingTransform
      - type: RandomRotate
        prob: 0.3
      - type: RandomErasing
        prob: 0.3
  sampler:
    batch_shuffle: true
    batch_size:
      - 8
      - 8
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  log_iter: 100
  optimizer_reset: true
  scheduler_reset: true
  exp_name: Exp_Name
  restore_hint: 0


evaluator_cfg:
  transform:
    - type: BaseSilCuttingTransform  
  sampler:
    batch_size: 8 
    sample_type: all_ordered
    type: InferenceSampler
  exp_name: Exp_Name
  restore_hint: 0

model_cfg:
  student: GaitGL
  teachers:
    - name: GaitSet
      restore_hint: 40000
      load_ckpt_strict: true
    - name: GaitPart
      restore_hint: 120000
      load_ckpt_strict: true
    - name: GaitGL
      restore_hint: 80000
      load_ckpt_strict: true
    # - name: Baseline_ResNet9
    #   restore_hint: 60000
    #   load_ckpt_strict: false
  teacher_eval: false  # use teacher.eval() or not